### ISSUE TITLE
pantry.core current build failures dashboard

### ISSUE THREAD

**Issue by mxcl** [teaxyz/pantry.core#112]
We promise to make everything in pantry.core build promptly, yet we have no proof we do that. We need some kind of “current failing builds in pantry.core” dashboard.

Ideally embeddable in the README.

**Comment by jhheider** [comment]
Yes, I think this is reasonably feasible. We just need to report new-version results (success and failure) out to our API, then have some way of rendering that data back to the README (the latter could prove interesting without constantly committing data back to git).

**Comment by mxcl** [comment]
Yeah so actually I think a simple badge of current failures vs. successful new-version builds this week. Because we have transparency with the auto-ticket-opening now.
