### ISSUE TITLE
`package.yml` template generator

### ISSUE THREAD

**Issue by jhheider** [teaxyz/pantry.core#142]
I started but am abandoning this for the moment: https://github.com/teaxyz/pantry.core/blob/%2Bnew.sh/scripts/new.sh

It could also be fruitfully done in some other language, and I think I'm convinced that not spreading the templates out will ease maintenance (and testing). Could also be down as a yeoman generator, if someone wanted to package `yo`.

**Comment by mxcl** [comment]
the place to do this is now https://github.com/teazyz/brewkit
