### ISSUE TITLE
Update bun to 0.5.6

### ISSUE THREAD

**Issue by perezd** [teaxyz/pantry.core#247]
https://bun.sh/blog/bun-v0.5.6

Is this something I can send a PR to do?

**Comment by jhheider** [comment]
Huh. Wonder why the build didn't trigger. Fired: https://github.com/teaxyz/pantry.core/actions/runs/4141459853

**Comment by jhheider** [comment]
Still erroring. Something in the test sequence seems to expect `node`: https://github.com/teaxyz/pantry.core/actions/runs/4141459853/jobs/7161097017

**Comment by jhheider** [comment]
Not a solid test, then.

**Comment by mxcl** [comment]
https://github.com/teaxyz/pantry.core/actions/runs/4164465737

**Comment by mxcl** [comment]
Closing as looks like it will pass. Reopen if not!
