### ISSUE TITLE
redeploy www if new bottle is deployed

### ISSUE THREAD

**Issue by getneil** [teaxyz/pantry.core#275]
`.github/workflows/new-version.yml` is triggered when there is a new package package bottled version

just add a step or script to trigger `www` redeploy after `index_data job` https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#re-run-a-job-from-a-workflow-run

**Comment by jhheider** [comment]
Would it be a better idea to have a more targeted job in `teaxyz/www` that can be run to update only the needed info? Redeploying the whole site (including CloudFront invalidations and uploading to S3) for every single bottle built (probably a dozen a day atm, -ish) seems like a probable excessive use of resources.

**Comment by getneil** [comment]
that is true. since new bottles rendered in www are only through the app.tea.xyz api already we should only trigger this process on new packages. 

though i managed to implement the process directly in kettle already https://github.com/teaxyz/kettle/pull/86 but GH www cd is triggered
