### ISSUE TITLE
Add exponential backoff to S3 uploads in upload.ts

### ISSUE THREAD

**Issue by jhheider** [teaxyz/pantry.core#32]
S3.putObject() likes to return 503s intermittently (but often enough to make our CD need painful reruns). [retried](https://deno.land/x/retried@1.0.1) or another library wrapping that function should help a lot.

**Comment by rossilor95** [comment]
Hey @jhheider! Can I work on this?

**Comment by jhheider** [comment]
Please do! We welcome community contributions, and anything tagged `help wanted` or `good first issue` would be especially useful starting points.

**Comment by rossilor95** [comment]
Hey @jhheider! 2 Questions: 

- Can I refactor `uploads.ts` to separate _functions_ and _main_ in 2 sections (e.g. like you folks did in [`ls.ts`](https://github.com/teaxyz/pantry.core/blob/05c0d227146b9e99a4f63ee40839e1b537925bc0/scripts/ls.ts#L26)? If so, I'll open a PR only to merge the refactoring.

- What's the best way to test `uploads.ts` once the exponential backoff to S3 uploads has been implemented?

Thanks! :D

**Comment by mxcl** [comment]
#176 is merged

**Comment by jhheider** [comment]
It's a good question on testing. Probably the right way is to set up an AWS s3 free tier, and run upload.ts. if it's working, then we're no worse off (hopefully). Hard to trigger the 503s, though you probably could with some proxy magic that even I wouldn't bother doing.

Refactoring is fine. Use your discretion about one vs many PRs. If it makes sense as a single PR and is legible, then that's fine.

**Comment by rossilor95** [comment]
Thank you very much for the hint! I'll give it a try 😃
