### ISSUE TITLE
Package go 1.18* 

### ISSUE THREAD

**Issue by regrowr** [teaxyz/pantry.core#402]
I'm intrigued by the premise of tea and started to replicate a hermit setup with tea, but hit this issue immediately:

```
$ tea +go.dev~1.18 sh
resolving package graph
error: not-found: pkg.version (spilt-tea-004)
we haven’t packaged this version. but we will… *if* you open a ticket:

    https://github.com/teaxyz/pantry.core/issues/new
```

go 1.17* and 1.19* are packaged but not 1.18* (or 1.16* & 1.20* for that matter).

Ideally at least 1 even numbered go version would be available, preferably 1.18* :-) 

TIA

**Comment by jhheider** [comment]
triggered builds for ~1.16, ~1.18, ~1.20. we do need a job that retroactively audits to ensure we've at least tried to build releases for the past year.

**Comment by jhheider** [comment]
Ah, right. `go.dev` has the cyclic dependency issue. This prevents building specific versions, but I have triggered a build of the most recent version (which will be 1.20.1 as of this writing).

The cyclic issue is https://github.com/teaxyz/brewkit/issues/15.

**Comment by jhheider** [comment]
And the fix is https://github.com/teaxyz/cli/pull/411. Once that passes, I'll build all the go minors since 1.16.

**Comment by jhheider** [comment]
Done: https://github.com/teaxyz/pantry.core/actions/runs/4308992584

Fixed by https://github.com/teaxyz/brewkit/pull/18
