### ISSUE TITLE
avoid rebottling

### ISSUE THREAD

**Issue by mxcl** [teaxyz/pantry.core#42]
1. PR builds and bottles
2. merged PR builds and bottles

I don’t see why the PR needs to bottle, am I missing something?

---

Long term we would obviously like to avoid rebuilding too.

**Comment by jhheider** [comment]
Only reason to bottle in the PR is to test as much as possible. On a merge, it seems like we must, as we may have made changes that require it.

**Comment by lino-levan** [comment]
I agree with @jhheider. What's the downside to rebottling? 

Possibly important question: Does it rebottle the whole pantry or just the diff?

**Comment by mxcl** [comment]
bottling doesn’t need testing though does it?

> On a merge, it seems like we must, as we may have made changes that require it.

yes, sorry if I wasn't clear. My issue is we are bottling in both the PR and the merge and we don't need to in the PR itself.

> What's the downside to rebottling?

It makes the checks take longer and checks taking too long slows down dev. Also it's wasteful, aren’t we trying to save the world?

> Possibly important question: Does it rebottle the whole pantry or just the diff?

It is just the diff.

**Comment by jhheider** [comment]
Easily pruned.
