### ISSUE TITLE
rebuilding on merge is actually more problematic

### ISSUE THREAD

**Issue by mxcl** [teaxyz/pantry.core#52]
The pantry is updated, so users can sync it, but there will be no package available until the rebuild occurs.

The builds from the PRs need to be used.

Ideally we'd use the artifacts.

**Comment by jhheider** [comment]
I have concerns about this:

- things might have changed with the CLI since the last artifact was built
- we might merge without letting the PR CI finish (rare)
- deps might have updated since the CI run
- locating the CI run during the merge (probably solvable)

I'll start digging into this. Assuming we can solve the last one, we can see how it works.

**Comment by jhheider** [comment]
Actually, the "easy" way might be to store the artifacts ourselves and just move them into place in our repository when done.

**Comment by jonchang** [comment]
>    things might have changed with the CLI since the last artifact was built

Not sure how this would affect builds?

>    we might merge without letting the PR CI finish (rare)

This can be handled with branch protections in github and required checks.

>    deps might have updated since the CI run

The bottles should track the list of dependencies it was built with and if necessary kick off a new build on merge.

>    locating the CI run during the merge (probably solvable)

This is only available through the graphQL API, https://docs.github.com/en/graphql/reference/objects, `associatedPullRequests`. It is fairly obnoxious to use and there will always be a race condition where it is possible that a user has a synced pantry but the artifact is not yet available for download. Can likely be solved with some retry logic in the client. (Homebrew does not use this since its bottles are updated as part of the commit tree itself, so the race condition is even worse)

**Comment by jonchang** [comment]
"Doing things on merge that are possibly fallible" will always be tricky on github. There will always need to be a compromise somewhere, which is really unfortunate. Other things I explored include:

* merging to a staging branch (possibly aided by bot) then having a CI process do the checks, then fast forward master/main if and only if CI passed on staging
* bot modifies user's pull request branch then does the merge
* move to a rebase workflow where the bot tests commits applied to HEAD locally then pushes commits atomically

**Comment by jhheider** [comment]
> >    things might have changed with the CLI since the last artifact was built
> 
> Not sure how this would affect builds?
> 

Could be any number of ways; but most of them would likely warrant a tree rebuild.

> >    we might merge without letting the PR CI finish (rare)
> 
> This can be handled with branch protections in github and required checks.
> 

Sure. I suppose the cases where we want to skip CI are likely few.

> >    deps might have updated since the CI run
> 
> The bottles should track the list of dependencies it was built with and if necessary kick off a new build on merge.
> 

Big idea. A good one, and extends even beyond this requirement.

> >    locating the CI run during the merge (probably solvable)
> 
> This is only available through the graphQL API, ...

Yeah, I think easy mode is staging them in the PR and then using them from our staging.

**Comment by jonchang** [comment]
In that case consider https://bors.tech/ if the staging branch idea is appealing. Not sure if it supports squash merges but but contributors do get the satisfaction of the purple "merged" button which is always a good thing and something that I had always hoped to implement for Homebrew but never got around to given the workflow compromises needed.

**Comment by jhheider** [comment]
I was thinking of just staging the artifacts (in S3 at the moment). I'll take a look at that.

**Comment by mxcl** [comment]
> Actually, the "easy" way might be to store the artifacts ourselves and just move them into place in our repository when done.

sounds like the solution to me.

---

I hear you on the concerns. Nothing strikes me as too bad though. You know me: protecting against user frustration comes first.

> things might have changed with the CLI since the last artifact was built

This is a wider issue we should solve with `libtea`. Coming Soon™!

In general I think @jonchang is right in that since we are only bottling tarballs, it should be safe. We aren't doing any other magic. Now potentially the build would have gone different, but protecting against that is a much larger matrix of hell that this is not the only way it effects us. Unless I'm not seeing it clearly?

> Not sure how this would affect builds? —@jonchang 

Because we use tea/cli sources for some build logic, we import this in CI.

> > > we might merge without letting the PR CI finish (rare)
> This can be handled with branch protections in github and required checks.
> Sure. I suppose the cases where we want to skip CI are likely few.

These should be rare, but also if for some reason the build isn't there we can manually trigger one thanks to your proactively adding that feature.

> > > deps might have updated since the CI run
> > The bottles should track the list of dependencies it was built with and if necessary kick off a new build on merge.
> Big idea. A good one, and extends even beyond this requirement.

[The receipt ticket](https://github.com/teaxyz/pantry/issues/6) was for this sort of thing.

The problem here of course is there's always some potential revlock with deps. There's no getting around it unless we version the pantry. We may want to version the pantry ofc (eventually).

---

Thanks for the thoughtful responses.

**Comment by jhheider** [comment]
"when to rebuild" is going to be the question for the ages, I think. It might not be the sort of thing the computer can know (without being wildly overcautious).

**Comment by mxcl** [comment]
we can correct errors until we know better.

However I just realized that stowing the bottles on S3 in a staging area could be risky. I would prefer to be able to nab the artifacts from the PR.

Surely there's a “merge event” which we can then get the artifacts from it and upload them.

**Comment by jonchang** [comment]
> Surely there's a “merge event” which we can then get the artifacts from it and upload them.

can use a gnarly graphql query for this. The API endpoint I linked above (associatedPullRequests)

**Comment by jhheider** [comment]
> This is only available through the graphQL API, https://docs.github.com/en/graphql/reference/objects, associatedPullRequests, then digging into the list of commits associated with the PR, then finding the CI run for that commit tip.

That sounds unreliable, but not impossible. What risks concern you about staging, @mxcl ?

**Comment by mxcl** [comment]
> What risks concern you about staging, @mxcl ?

It's asking for some bug where a stale bottle from a previous run gets published and breaks stuff. Potentially a hacking vector too (though admittedly I see not how, it is though a potential vector)
