### ISSUE TITLE
Python should also provide `pythonx.y`

### ISSUE THREAD

**Issue by nihaals** [teaxyz/pantry.core#66]
I'm not sure if this is the right repo for this issue since this might not be supported by tea, but Python (and Pip) normally also provides `pythonx.y` (and `pipx.y`), for example `python3.11`. Currently, only `python` and `python3` are provided. This is relevant for both being inside a tea environment, and `tea -X` (where a specific version can be inferred, for example `~3.11`, which might make sense to be split into another issue).

**Comment by mxcl** [comment]
```sh
$ tea +python.org 
tea: installed: ~/.tea/invisible-island.net/ncurses/v6.3.0
tea: installed: ~/.tea/gnu.org/readline/v8.1.0
tea: installed: ~/.tea/sourceware.org/libffi/v3.4.4
tea: installed: ~/.tea/libexpat.github.io/v2.5.0
tea: installed: ~/.tea/bytereef.org/mpdecimal/v2.5.1
tea: installed: ~/.tea/sqlite.org/v3.40.0
tea: installed: ~/.tea/python.org/v3.11.1
tea: installed: ~/.tea/pip.pypa.io/v22.3.0
this is a temporary shell containing the following packages:
zlib.net@1.2.13, sourceware.org/bzip2@1.0.8, openssl.org@1.1.118, tukaani.org/xz@5.2.7, invisible-island.net/ncurses@6.3.0, gnu.org/readline@8.1.0, sourceware.org/libffi@3.4.4, libexpat.github.io@2.5.0, bytereef.org/mpdecimal@2.5.1, sqlite.org@3.40.0, python.org@3.11.1, pip.pypa.io@22.3.0
when done type: `exit'

tea$ which python
/Users/mxl/.tea/python.org/v3.11.1/bin/python
tea$ which python3
/Users/mxl/.tea/python.org/v3.11.1/bin/python3
tea$ which python3.11
/Users/mxl/.tea/python.org/v3.11.1/bin/python3.11

tea$ which pip
/Users/mxl/.tea/pip.pypa.io/v22.3.0/bin/pip
tea$ which pip3
/Users/mxl/.tea/pip.pypa.io/v22.3.0/bin/pip3

tea$ which pip3.11
pip3.11 not found
```

So yeah it's just pip. One issue here is we are independently packaging pip and python. So strictly the python version that is loaded may not be eg. `3.11`.

Probably it's just that `tea -X python3.11` is not working, and that's because our `provides` matrix is not able to version currently. Let me see if I can fix that…

**Comment by nihaals** [comment]
I'm not sure how I managed, but when I was first testing `tea --env --dump`, tea didn't edit my PATH and only added a command not found handler, which is how I got this behaviour and assumed being inside an environment also uses `provides`, but now it works fine for `pythonx.y`.

**Comment by mxcl** [comment]
> tea didn't edit my PATH and only added a command not found handler

right, this makes sense. I’ll add a ticket to track this. If a package isn't installed we add the command-not-found handler to install it if the user should type `foo`, but we don’t add them for versioned binaries.

Probably there is a better way to do this. I'll ticket up the bug on tea/cli

**Comment by nihaals** [comment]
I haven't explored how tea works with Pip since it's tied to a specific Python install but should this issue be split to track adding `pipx.y` too? This would need to affect the Python install Pip targets but not Pip's version.

**Comment by mxcl** [comment]
we have eg. `pip3` I don’t think we can easily add `pip3.11`, but we will if it is common. How commonly do people use eg. `pip3.11`?

**Comment by nihaals** [comment]
It's more of a thing when you have multiple Python installs, in which case the only alternative is `python -m pip`. There is a current workaround of adding a shell alias for `pipx.y` to `pythonx.y -m pip` though if people need it, and that will make using the correct install more precise. I think tools like [Poetry](https://github.com/python-poetry/poetry) use `python -m pip` internally since some systems don't have `pip` set up properly, so not supporting `pipx.y` shouldn't break any major tools, but I haven't tried and because of how Pip works and where it installs packages, using tea for it feels a bit more unnatural compared to e.g. Cargo which has set directories for both global installs and project dependencies.

**Comment by mxcl** [comment]
tea will always use the specifically requested pip and python versions ofc. So in this case won’t it be the case that it doesn’t matter?

**Comment by nihaals** [comment]
Since you can have different packages installed for each minor Python version, someone might want to use Pip with a specific Python version to manage that version's dependencies, and because of things like wheels and breaking changes, you might not want to immediately use the latest Python version when using Pip, so giving a nice way to say something like "Latest Pip with Python 3.10 (and install packages in 3.10's directory)" and "Latest Pip with Python 3.11 (and install packages in 3.10's directory)" would be fairly important. I'm not sure what the current solution for this is, but one way (which is probably harder to implement) would be `tea -X pip3.10` and `tea -X pip3.11`. You could also just alias to `tea -X python3.10 -m pip` which I don't think would require any changes to the current implementation unless Pip doesn't use the correct Python location which I haven't tested yet.

I'm not sure what most users would want and what's worth the implementation work at the moment so it might make sense to wait until more Pip users have tried tea to give their feedback as I personally use wrappers like Poetry to handle venv creation and dependency management. The important core concept is wanting a specific version of pip set up with a specific version of Python though. I haven't looked into how pip determines which directory/Python install it uses before but in a typical install they're usually in the same directory and each Python install has its own pip so that the pip works for the corresponding Python install.

**Comment by jonchang** [comment]
Based on my experience with python, running naked `pip` or even versioned `pip3.11` is extremely dangerous given that any upgrade of pip will spray pip's links everywhere, so you have no idea which version of python you'll be installing pip with. Users should generally prefer using `tea -X python3.11 -mpip install` to ensure that they're getting the expected version of python with their pip installs.

**Comment by mxcl** [comment]
you can specify specific versions of pip with tea `tea +pypa.org/pip^1.2.3` of course. Which seems like it satisfies your needs @nihaals

and like @jonchang probably any other way is dangerous anyway.

**Comment by nihaals** [comment]
> you can specify specific versions of pip with tea `tea +pypa.org/pip^1.2.3` of course. Which seems like it satisfies your needs

The important control with Pip is actually configuring the Python version as opposed to the Pip version. I'm wondering if this can lead to a bug based on Pip being configured for a different version of Python than the one installed, as I'm not entirely sure where Pip sets it. I'll see if I can get a MWE to work. If not then I don't think this is an issue.

**Comment by mxcl** [comment]
> I'm wondering if this can lead to a bug based on Pip being configured for a different version of Python than the one installed

tea is designed to have package specify exactly what versions of dependencies they support so if pip specifies it's python requirements properly on a per pip version basis then things are fine.

> I'll see if I can get a MWE to work. If not then I don't think this is an issue.

Excited to here about how you get on!

**Comment by nihaals** [comment]
After experimenting, it seems like pip is always set to the correct site-packages path so I don't think any further changes are needed unless people want `pipx.y` (in either `tea -X` or in an environment).
