### ISSUE TITLE
Changes to build-deps.ts break true cyclic dependencies

### ISSUE THREAD

**Issue by jhheider** [teaxyz/pantry.core#80]
972f0715f40794693dc53d5ea2df39cf99fa6732 breaks zlib.net build on linux: https://github.com/teaxyz/pantry.core/actions/runs/3744295008/jobs/6357592962, because

zilb =req> llvm =req> zlib.

Reverting in https://github.com/teaxyz/pantry.core/pull/78 until we can work out the proper algo.

**Comment by mxcl** [comment]
Fixed with #82
