### ISSUE TITLE
Write a simple tea-script frontend to teaxyz/cli:src/utils/semver.ts

### ISSUE THREAD

**Issue by jhheider** [teaxyz/pantry.core#99]
This would allow more reliable/simpler testing of versions within build scripts, such as:

https://github.com/teaxyz/pantry.core/blob/main/projects/deno.land/package.yml

https://github.com/teaxyz/pantry.core/blob/main/projects/rust-lang.org/package.yml

**Comment by mxcl** [comment]
Is the title meant to be for `utils/semver.ts`?

**Comment by jhheider** [comment]
crap.
